### ISSUE TITLE
File size check 

### ISSUE THREAD

**Issue by lijiang2014** [JiangLiNSCC/eHPC#1]
对于上传的文件，需要限制大小，但目前并无这方面的策略。
Django 的 POST 方法的 File Upload 是可以进行的，但目前 restful API 用 PUT 来上传， 暂时没找到好的方式。

**Comment by lijiang2014** [comment]
File 相关的API 可能得单独设计 。

**Comment by JiangLiNSCC** [comment]
http://stackoverflow.com/questions/5731984/how-do-i-handle-file-upload-via-put-request-in-django
目前限制了上传文件的大小。
针对大文件应该提供断点上传的功能，暂时可不考虑这里。
