### ISSUE TITLE
API 接口文档

### ISSUE THREAD

**Issue by xuelangZF** [JiangLiNSCC/eHPC#19]
我们整理了一份 API 接口文档，你看有没有什么问题呢？

[超算接口说明文档](https://github.com/xuelangZF/ehpc/wiki/%E8%B6%85%E7%AE%97%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E%E6%96%87%E6%A1%A3)

**Comment by lijiang2014** [comment]
看了下，写的很不错！

**Comment by xuelangZF** [comment]
好像有的接口又有了改动？

![image](https://cloud.githubusercontent.com/assets/2769831/21580238/412628aa-d021-11e6-8f02-be0c7945653c.png)  

返回的是 201，按照文档中说法，表示已经加入了队列，可以异步获取，我接着用 aync 试着获取,

![image](https://cloud.githubusercontent.com/assets/2769831/21580243/87ff90d6-d021-11e6-9084-3bcb46961dcb.png)

结果表示还是没有内容，无法获取目录。不知道是不是因为接口有了改动？

**Comment by JiangLiNSCC** [comment]
没有啊，你出错了 ： 

async 不是 aync 





------------------


------------------------------
* 典型性问题欢迎到下面的网址进行提问和搜索 ！
* https://github.com/JiangLiNSCC/TH2-demos/issues （推荐）
* Links : docs 搜索已有问题  提新问题
* 办公时间可联系： 020-37106035 （不推荐）
* 李江  国家超级计算广州中心/广州超级计算中心/应用部
* 广州市番禺区大学城外环东路132号






 

 
 
 
------------------ Original ------------------

**Comment by xuelangZF** [comment]
。。多谢！  我的错。。
