### ISSUE TITLE
关于新帐号的测试和密码

### ISSUE THREAD

**Issue by milanlanlan** [JiangLiNSCC/eHPC#23]
你好，如果可以开始测试请在这里提醒我，另外可不可以麻烦一下您查一下sysu_hpc_dwu_1这个帐号的密码呢？因为这边还没有实现用密钥登录的代码。谢谢！

**Comment by JiangLiNSCC** [comment]
这个我得找管理员那边处理一下，搞好了给你说，你先用原来的帐号的，到时候换新的即可 





------------------


------------------------------
* 典型性问题欢迎到下面的网址进行提问和搜索 ！
* https://github.com/JiangLiNSCC/TH2-demos/issues （推荐）
* Links : docs 搜索已有问题  提新问题
* 办公时间可联系： 020-37106035 （不推荐）
* 李江  国家超级计算广州中心/广州超级计算中心/应用部
* 广州市番禺区大学城外环东路132号






 

 
 
 
------------------ Original ------------------

**Comment by milanlanlan** [comment]
你好，我今天测试了一下，不知道download接口（PUT /api/file/<machine/<path>?download=True>）现在是不是不会返回key为status_code的值呢？因为这边在测试
```
`self.open("/file/" + machine_name + "/%s?download=True" % async_id)`时，
self.status_code = rdata["status_code"]返回了typeError: string indices must be integers
```
还是说因为我在哪里疏忽了没有注意到接口的变化呢？
此外，调用job的时候返回了 
`run: error: unable to create job step: Requested node configuration is not available，`
不知道是什么问题呢？

打扰了，谢谢！

**Comment by milanlanlan** [comment]
上面那个 run：error 是 srun：error

**Comment by JiangLiNSCC** [comment]
`self.open("/file/" + machine_name + "/%s?download=True" % async_id)`  
这个返回的结果是一个文件数据流（方便文件的传输），而非一个json 字符串，所以会有此错误。（其他的API返回都是了）


`srun: error: unable to create job step: Requested node configuration is not available，`

这是说脚本调用的资源有问题，你的提交脚本是怎么写的 ？ 




------------------


------------------------------
* 典型性问题欢迎到下面的网址进行提问和搜索 ！
* https://github.com/JiangLiNSCC/TH2-demos/issues （推荐）
* Links : docs 搜索已有问题  提新问题
* 办公时间可联系： 020-37106035 （不推荐）
* 李江  国家超级计算广州中心/广州超级计算中心/应用部
* 广州市番禺区大学城外环东路132号






 

 
 
 
------------------ Original ------------------

**Comment by lijiang2014** [comment]
我这几天测试 JOB API 没什么问题的，你把 你提交任务的那块发我看看吧。或者你们可以参考下我昨天发给你们的文档。 
另外今天更新了2个API :
1. post /api/job/<machine> 现在在POST 表单里可以通过 jobfilepath 来指定 script 文件的位置 ，如： 
```
mc.open("/job/" + machine_name + '/' , data = {"jobscript" : test_batchstr , "jobfilepath" : '/HOME/%s/project/testjob/job.sh' % login_data["username"]  })
```
2. get /api/job/<machine>/<jobid> 现在可以返回详细的内容 ，如：
```
{u'status': u'OK', u'status_code': 200, u'output': {u'4304226': {u'AveCPUFreq': u'', u'MaxDiskWrite': u'', u'JobName': u'newt_o2qgr2zi', u'MaxRSS': u'', u'State': u'PENDING', u'ConsumedEnergy': u'', u'MaxVMSizeNode': u'', u'AveRSS': u'', u'MinCPUTask': u'', u'MaxDiskReadNode': u'', u'AveVMSize': u'', u'MaxDiskReadTask': u'', u'MaxDiskRead': u'', u'Elapsed': u'00:00:00', u'MaxVMSizeTask': u'', u'MaxVMSize': u'', u'AveDiskRead': u'', u'MaxPagesNode': u'', u'MaxPagesTask': u'', u'Partition': u'work', u'MinCPUNode': u'', u'MaxDiskWriteTask': u'', u'AveCPU': u'', u'JobID': u'4304226', u'MaxDiskWriteNode': u'', u'MaxRSSNode': u'', u'MinCPU': u'', u'ReqMem': u'0n', u'ReqCPUFreq': u'', u'NTasks': u'', u'AvePages': u'', u'MaxRSSTask': u'', u'AllocCPUS': u'48', u'MaxPages': u'', u'AveDiskWrite': u'', u'ExitCode': u'0:0'}}, u'error': u''}
```
其中可能很多是没有用的信息 ，由于一个作业会有多个作业步，所以这里的信息看起来很多。（由于这个作业运行时间太短，时间记录为0）

**Comment by lijiang2014** [comment]
你们现在测试生成的作业脚本的路径是哪里？ 我去看下就知道哪里有问题了 。

**Comment by milanlanlan** [comment]
有可能是因为之前status_code部分出错导致后面的错误，我再调试看看，谢谢！

**Comment by lijiang2014** [comment]
我看了一下，你们似乎还是用的之前的帐号（sysu_dwu_1）, 然后提交的作业文件是 ： '/HOME/sysu_dwu_1/workdir/job.sh' . 内容为 ：

```
#!/bin/sh
#SBATCH -N 1
srun -N 1 -n 4 ./a.out  > log.srun.a
```

然而这个文件夹中并没有 a.out . （a.out 是在 ~/coreos/ ？）

现在你们的计算逻辑似乎是都是在一个固定的文件夹里面运行，这样的处理会导致平台同时只能服务一个用户，不然会相互干扰。

建议用户的每一个单元的操作（编译、提交执行）在各自独立的文件夹中进行，并定期清理。

**Comment by milanlanlan** [comment]
没有啊，我已经改成了sysu_hpc_dwu_1，而且用yhrun的接口已经成功测试了2400核的例子了（以前的帐号没有那么多节点资源），目前的路径是/HOME/sysu_dwu_1/project/ehpc，请问这个路径存在吗？因为现在的返回结果是ERRNO21 is a directory:/tmp/tmpfile.有点奇怪

**Comment by lijiang2014** [comment]
你用 sysu_hpc_dwu_1 这个帐号怎么访问 /HOME/sysu_dwu_1/project/ehpc 下面的文件呢 ？

**Comment by milanlanlan** [comment]
也可以正常返回jobid，例如最近一次是4307645

**Comment by milanlanlan** [comment]
哦哦，这里是我打错了， 是/HOME/sysu_hpc_dwu_1/project/ehpc才对，不好意思

**Comment by lijiang2014** [comment]
@milanlanlan 

```
[sysu_hpc_dwu_1@ln2%tianhe2-C ~]$ yhacct -j 4307645
       JobID    JobName  Partition    Account  AllocCPUS      State ExitCode 
------------ ---------- ---------- ---------- ---------- ---------- -------- 
4307645          job.sh       work sysu_hpc_+         24  COMPLETED      0:0 
4307645.bat+      batch            sysu_hpc_+          1  COMPLETED      0:0 
```

可以看到其实你们只申请到了1个节点的资源，所以：

```
[sysu_hpc_dwu_1@ln2%tianhe2-C ~]$ cat project/ehpc/job.sh 
#!/bin/bash
    #SBATCH -p work
    #SBATCH -N 200
    date
    time srun -n 2400 -c 1 ./ab.out
    date[sysu_hpc_dwu_1@ln2%tianhe2-C ~]$ 

```

在提交 2400 核的时候出错了 （资源不足） 。

为什么没有申请到 更多的节点呢 ，抱歉，是我之前给你们发的范例里有个地方没处理好 ：

```
    jobscript = """#!/bin/bash
    #SBATCH -p %s
    #SBATCH -N %s
... 
```

这里由于缩进的原因，附加脚本里也错误的带进去了缩进，写成 ：

```
    jobscript = """#!/bin/bash
#SBATCH -p %s
#SBATCH -N %s
... 
```

应该就OK 了。 

如： 
```
[sysu_hpc_dwu_1@ln2%tianhe2-C ehpc]$ yhbatch job2.sh 
Submitted batch job 4307802
[sysu_hpc_dwu_1@ln2%tianhe2-C ehpc]$ yhq
             JOBID PARTITION     NAME         USER ST       TIME  NODES NODELIST(REASON)
           4307802      work  job2.sh sysu_hpc_dwu PD       0:00    200 (None)
[sysu_hpc_dwu_1@ln2%tianhe2-C ehpc]$ cat job2.sh 
#!/bin/bash
#SBATCH -p work
#SBATCH -N 200
    date
    time srun -n 2400 -c 1 ./ab.out
    date
[sysu_hpc_dwu_1@ln2%tianhe2-C ehpc]$ 

```
虽然作业还在排队，不过可以看到已经可以正确的请求200个节点的资源了  ：） 。

**Comment by milanlanlan** [comment]
好的，我试试！

**Comment by milanlanlan** [comment]
还是不行，请问应该这样写吗？此外我还试过将#的两行前面的缩进去掉，也还是同样的结果
```
def submit_job(self, myPath, job_filename, output_filename, node_number=1, task_number=1, cpu_number_per_task=1,  partition="work"):
        jobscript = """#!/bin/bash
    #SBATCH -p %s
    #SBATCH -N %s
        date
        time srun -n %s -c %s ./%s
        date""" % (partition, node_number, task_number, cpu_number_per_task, output_filename)
```

**Comment by milanlanlan** [comment]
这里的def应该是和#对齐的，不好意思！

**Comment by lijiang2014** [comment]
@milanlanlan  可以了吗？

**Comment by milanlanlan** [comment]
还是不行，依然是errno21，最新一次jobid是4308377，而且有时会出现request失败或者self.ouput["jobid"]的typeerror:string induces...

**Comment by lijiang2014** [comment]
@milanlanlan 
你的 job.sh 还是有问题啊 ： 

```
[sysu_hpc_dwu_1@ln2%tianhe2-C ehpc]$ cat job.sh 
#!/bin/bash
    #SBATCH -p work
    #SBATCH -N 200
        date
        time srun -n 2400 -c 1 ./ab.out
        date[sysu_hpc_dwu_1@ln2%tianhe2-C ehpc]$ 
```

**Comment by milanlanlan** [comment]
我现在把#SBATCH前面的空格全部去掉了再提交一次，也就是：
   ```
     def submit_job(self, myPath, job_filename, output_filename, node_number=1, task_number=1, cpu_number_per_task=1,  partition="work"):
        jobscript = """#!/bin/bash
#SBATCH -p %s
#SBATCH -N %s
    date
    time srun -n %s -c %s ./%s
    date""" % (partition, node_number, task_number, cpu_number_per_task, output_filename)
```
还是一样的错误，不知道怎么样了呢？

**Comment by JiangLiNSCC** [comment]
我看这次是正常算完了啊，（不过由于资源请求的比较大，排队的时间稍长一点儿）


```
[sysu_hpc_dwu_1@ln2%tianhe2-C ehpc]$ tail  slurm-4308452.out 
Hello World!I'm rank 1472 of 7 on cn12011
Hello World!I'm rank 1471 of 7 on cn12011
Hello World!I'm rank 1473 of 7 on cn12011
Hello World!I'm rank 1474 of 7 on cn12011
Hello World!I'm rank 1475 of 7 on cn12011


real	0m2.736s
user	0m0.479s
sys	0m0.215s
Thu Jan 12 15:47:21 CST 2017
[sysu_hpc_dwu_1@ln2%tianhe2-C ehpc]$ 


```

**Comment by milanlanlan** [comment]
但是我这里的返回结果依然是status_code=500，output里的error是[errno21]Is a directory: '/tmp/tmpfile/'，难道因为排队的时候我们这边需要多等一段时间？我的实现是获取jobid后马上传给download函数。

**Comment by JiangLiNSCC** [comment]
这样是有问题的，PD 状态下 还没有创建 slurm-<id>.out文件，所以会出错，不过你可以设置个刷新，重新去获取或下载这个文件。
更好的办法是： 
先去检查状态，状态为成功或失败后去下载文件，不然就显示（在等待分配资源/在运行中）。如果已经开始计算了，也可以去下载结果，不过可能文件不完整。




------------------


------------------------------
* 典型性问题欢迎到下面的网址进行提问和搜索 ！
* https://github.com/JiangLiNSCC/TH2-demos/issues （推荐）
* Links : docs 搜索已有问题  提新问题
* 办公时间可联系： 020-37106035 （不推荐）
* 李江  国家超级计算广州中心/广州超级计算中心/应用部
* 广州市番禺区大学城外环东路132号






 

 
 
 
------------------ Original ------------------

**Comment by milanlanlan** [comment]
好的，我知道了！

**Comment by milanlanlan** [comment]
你好，我直接设置sleep函数后发现是可以正常返回结果的，但是我在尝试设置对state状态的判断的时候发现输出是
`{u'status': u'OK', u'status_code': 200, u'output': {}, u'error': u''}`
此时的-n 24 -N 2,规模比较小
但是当规模大的时候发现获取self.output["State"]返回keyerror,不知道应该怎么获取呢？
谢谢！

**Comment by milanlanlan** [comment]
你好，我发现了是self.output[str(jobid)]["State"]，现在可以了！谢谢
