### ISSUE TITLE
daemon 

### ISSUE THREAD

**Issue by lijiang2014** [JiangLiNSCC/eHPC#26]
编写守护进程，以进行下列工作 ：
* 启动 / 杀死 / 重启  webserver 
* 启动 / 杀死 / 重启 worker 
*   定期执行任务 ：
    * 删除过期的临时资源
    * 监控资源用量
    * 定期进行测试，并根据测试结果进行 （ 发邮件通知 /重启应用环境）

**Comment by lijiang2014** [comment]
已完成通过supervisor 实现前两条功能。
监控功能也将基于supervisor 进行，但非核心功能，可能会如同tests 进行独立。

**Comment by lijiang2014** [comment]
合并 #10 的任务： 
清理临时资源： 
TEMPFILE
CACHE
MQ RESULT
Server State .

**Comment by JiangLiNSCC** [comment]
目前完成了其中一部分： 定期进行测试 。
webserver 状态的监控和临时资源的删除还有待完成。

**Comment by JiangLiNSCC** [comment]
https://github.com/JiangLiNSCC/eHPC/wiki/manager-%E4%B8%8E-monitor
