### ISSUE TITLE
关于api的一些问题

### ISSUE THREAD

**Issue by milanlanlan** [JiangLiNSCC/eHPC#6]
您好 目前我简单地测试了三个api
login方面是没有问题的。
至于上传文件，我的命令是curl -T ../main.c http://hpc-api-server/api/file/workdir/main.c，这里返回的是一个django的提示：You're seeing this error because you have <code>DEBUG = True</code>，似乎是后台方面设置debug模式的问题，不知道我们这边需要输入怎样的命令还是怎样调整呢？希望更新一下api的接口命令。
最后我测试的是调试命令：curl -X POST -d "command=mpicc main.c -o a.out" -b cookie.txt http://hpc-api-server/api/command/localhost
原本我以为错误会是没有找到main.c，然而返回的是403，提示信息是：you must be logged in to acess this.但是我在之前已经用第一个命令登录过了，不知道这是什么问题呢？
此外，希望提供makefile方面的接口文档，谢谢！

**Comment by xuelangZF** [comment]
curl 应该是不带状态的，你之前登录和现在的这次post没有关系

**Comment by xuelangZF** [comment]
可以用 requests 库的session 来维护不同请求之间的状态

**Comment by lijiang2014** [comment]
大部分的API 需要先登陆才能使用的，在使用的过程中需要附带登陆获得的token 信息。现在我的 服务可能其他账号用的过程中一些API 用不了。你们把你们的 天河账号的秘钥文件发我一下吧。我用你们的账号也起一个服务，这样才能调试所有的API。

**Comment by lijiang2014** [comment]
抱歉，看到你们的秘钥文件已经发过来了 。

**Comment by lijiang2014** [comment]
使用范例 
http://note.youdao.com/noteshare?id=1d21647e43cf4f8294bbfcc41b86ff21

**Comment by JiangLiNSCC** [comment]
好的，麻烦你们多测一测了 。有问题就在github 上留言。 会根据你们的意见进行下一步的改进。 






------------------


------------------------------
* 典型性问题欢迎到下面的网址进行提问和搜索 ！
* https://github.com/JiangLiNSCC/TH2-demos/issues （推荐）
* Links : docs 搜索已有问题  提新问题
* 办公时间可联系： 020-37106035 （不推荐）
* 李江  国家超级计算广州中心/广州超级计算中心/应用部
* 广州市番禺区大学城外环东路132号






 

 
 
 
------------------ Original ------------------
