### ISSUE TITLE
Some problems.

### ISSUE THREAD

**Issue by milanlanlan** [JiangLiNSCC/eHPC#7]
1. api文档中，[http://cn16356:8000/api](url)不能访问，而[http://10.172.48.5:8000/api](url)应该是[http://10.127.48.5:8000/api](url)才对。

2. 关于**编译/执行**方面，_gcc_是可以的，但是用_mpicc_会返回“command not found”，不知道是不是我写的有些问题。希望可以给出_mpicc/openmp_的使用样例。

3. 一个很奇怪的问题。直接在终端上测试所有命令都是可行的，但我进一步把每个api封装成函数依次调用的时候，**编译/执行**命令会提示说没有登录（403）无法执行命令，而**登录、上传和查看**可以。按理说，每个请求都是通过cookie.txt进行验证，即使分开调用或者登录出了问题，也不会发生可以**上传**而不可以**编译/执行**的情况才对。我想了想，应该是**编译/执行**命令中需要在_ehpc_服务器直接调用_bash_命令而没有权限的问题，希望得到解答。

**Comment by lijiang2014** [comment]
1. 已修复。 cn16356 是天河内部的hostname , 10.127.48.5 是其配置的以太网IP
2. 调用 mpicc 返回 command not found 是因为目前是测试环境，没有真的在ln3 上起 worker ， 没有Mpicc . 如果你们现阶段测试没问题，我会申请一个root 的 Ln 权限进行更加真实的测试 
3. 可以看一下你是怎么封装的吗？

**Comment by milanlanlan** [comment]
以下是编译的代码
```
 def compile_ehpc(input_filename, path, language = "gcc", output_filename = "a.out", machine = "ln3"):
     request_url = base_url + "/command/" + machine

     compile_command = {
             "gcc" : "gcc %s -o %s" % (input_filename, output_filename),
             "mpicc" : "mpicc %s -o %s" % (input_filename, output_filename)
     }
 
     commands = 'curl -X POST --data-urlencode \'command=bash -i -c \"cd %s;%s\"\'-b cookie.txt %s' % (path, compile_command[language], reque    st_url)
     p = subprocess.Popen(commands, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
     stdout, stderr = p.communicate()
 
     result = json.loads(stdout)
 
     if result["status"] == "ACCEPT" :
         return "Success!The id is %s" % (result["output"])
     else :
         return "Compile error!The error is %s" % (result["error"])

```

**Comment by lijiang2014** [comment]
不建议通过命令拼接的方式来使用API ， 你可以参考我现在正在写的 API 测试代码的框架 来使用API , 不过今天只写了一部分，预计明天可以写完目前所有的测试。
测试代码所在路径：
/HOME/sysu_dwu_1/apitests/pytest/main.py
测试环境目前没有 MPICC 环境，建议暂时先进行其他的测试，这周有时间一起开会讨论一下？

**Comment by milanlanlan** [comment]
@lijiang2014 
好的，我这些做的不多，回去学习一下。
讨论的话，我不知道其他人是否有空，我个人没有问题

**Comment by lijiang2014** [comment]
那就這周五上午吧，不用那麼多人的，你們需要用的來一兩個就行了。 @milanlanlan

**Comment by milanlanlan** [comment]
@lijiang2014 
好的，不知道具体是几点呢？

**Comment by JiangLiNSCC** [comment]
10：00 如何 ？ 






------------------


------------------------------
* 典型性问题欢迎到下面的网址进行提问和搜索 ！
* https://github.com/JiangLiNSCC/TH2-demos/issues （推荐）
* Links : docs 搜索已有问题  提新问题
* 办公时间可联系： 020-37106035 （不推荐）
* 李江  国家超级计算广州中心/广州超级计算中心/应用部
* 广州市番禺区大学城外环东路132号






 

 
 
 
------------------ Original ------------------

**Comment by milanlanlan** [comment]
好的，没有问题

**Comment by milanlanlan** [comment]
@lijiang2014 
好像没有办法进入想要进入的目录，例如`cd /HOME/sysu_dwu_1`会permission denied，登录也没有报错，而且也无法使用pwd命令，所以我不知道哪个目录才可以用，还是说我哪里弄错了吗？代码就是用你提供的测试文档

**Comment by JiangLiNSCC** [comment]
好的，我周一看看是怎么回事。






------------------


------------------------------
* 典型性问题欢迎到下面的网址进行提问和搜索 ！
* https://github.com/JiangLiNSCC/TH2-demos/issues （推荐）
* Links : docs 搜索已有问题  提新问题
* 办公时间可联系： 020-37106035 （不推荐）
* 李江  国家超级计算广州中心/广州超级计算中心/应用部
* 广州市番禺区大学城外环东路132号






 

 
 
 
------------------ Original ------------------

**Comment by milanlanlan** [comment]
好的，不过不知道可不可以给一个可以让我测试的路径呢？
很抱歉，不过我们这边进度催得有些紧，不好意思

**Comment by lijiang2014** [comment]
你现在再试试，：
mc.open("/command" + machine_name , data = { "command" : "bash -c 'cd /HOME/sysu_dwu_1/coreos;pwd' "})

**Comment by lijiang2014** [comment]
周末我在家里连服务器不方便，测试请尽量放在周一到周五吧。
> 之前的代码示例里执行组合命令用的是bash -i -c 参数，现在由于环境变量没有完全设置好，$HOME=/root ,  使用 -i 参数会去执行 $HOME/.bashrc 脚本，导致 Permission denied.

**Comment by milanlanlan** [comment]
你好，现在好像可以正常进入了，不过我想请问一下`upload_file（api: PUT /api/file/<macchine>/<path>）`这个函数。
例如，`mc.open("/file/" + machine_name + '/root/' + filename , method = "PUT" , data = testdata   )`中的参数data是指是指上传的内容而不是文件名对吗？我发现无论如何也不能正常上传，例如`ls main.c`然后我用ls命令看了一下那边的目录，好像上传过去的文件名前面都加上了n，例如上传main.c会变成nmain.c，还是说这只是传输编码上的错误呢？
此外，出于好奇，我尝试直接编译nmain.c这个命令，会报出一堆错误，这个错误我查了一下，好像是gcc库安装不完全或者那个目录没有源文件引起的，所以现在我不是很确定到底是哪个错误，希望可以解决这个问题。
麻烦了。

**Comment by JiangLiNSCC** [comment]
稍等，我看下是怎么回事






------------------


------------------------------
* 典型性问题欢迎到下面的网址进行提问和搜索 ！
* https://github.com/JiangLiNSCC/TH2-demos/issues （推荐）
* Links : docs 搜索已有问题  提新问题
* 办公时间可联系： 020-37106035 （不推荐）
* 李江  国家超级计算广州中心/广州超级计算中心/应用部
* 广州市番禺区大学城外环东路132号






 

 
 
 
------------------ Original ------------------

**Comment by JiangLiNSCC** [comment]
我测试的结果是正常的呀


mc.open("/file/ln3/HOME/sysu_dwu_1/main.c' , method = "PUT" , data = 'main.c' )


你把你的那个命令语句发我看下？









------------------


------------------------------
* 典型性问题欢迎到下面的网址进行提问和搜索 ！
* https://github.com/JiangLiNSCC/TH2-demos/issues （推荐）
* Links : docs 搜索已有问题  提新问题
* 办公时间可联系： 020-37106035 （不推荐）
* 李江  国家超级计算广州中心/广州超级计算中心/应用部
* 广州市番禺区大学城外环东路132号






 

 
 
 
------------------ Original ------------------

**Comment by milanlanlan** [comment]
哦哦，我以为参数data是main.c的内容而不是文件名，我重新测试看看。抱歉。

**Comment by JiangLiNSCC** [comment]
data 是内容 ， 你没理解错 。。






------------------


------------------------------
* 典型性问题欢迎到下面的网址进行提问和搜索 ！
* https://github.com/JiangLiNSCC/TH2-demos/issues （推荐）
* Links : docs 搜索已有问题  提新问题
* 办公时间可联系： 020-37106035 （不推荐）
* 李江  国家超级计算广州中心/广州超级计算中心/应用部
* 广州市番禺区大学城外环东路132号






 

 
 
 
------------------ Original ------------------

**Comment by milanlanlan** [comment]
```
def upload(self, path, filename, data):
    tmpdata = self.open("/file/" + machine_name + path + '/' + filename, method="PUT", data=data)
```
其中，machine_name="ln3", path=“/HOME/sysu_dwu_1/coreos”, filename="main.c"
然后返回的也是200 OK，但之后编译就好像找不到文件，再用ls main.c也是no such file..

**Comment by JiangLiNSCC** [comment]
我在 /HOME/sysu_dwu_1/coreos 下面是能看到 main.c 文件的呀 






------------------


------------------------------
* 典型性问题欢迎到下面的网址进行提问和搜索 ！
* https://github.com/JiangLiNSCC/TH2-demos/issues （推荐）
* Links : docs 搜索已有问题  提新问题
* 办公时间可联系： 020-37106035 （不推荐）
* 李江  国家超级计算广州中心/广州超级计算中心/应用部
* 广州市番禺区大学城外环东路132号






 

 
 
 
------------------ Original ------------------

**Comment by JiangLiNSCC** [comment]
不过 你的 main.c 的内容不正确， data 要是文件的内容。 
所以编译过程和运行过程没有正确进行 



------------------


------------------------------
* 典型性问题欢迎到下面的网址进行提问和搜索 ！
* https://github.com/JiangLiNSCC/TH2-demos/issues （推荐）
* Links : docs 搜索已有问题  提新问题
* 办公时间可联系： 020-37106035 （不推荐）
* 李江  国家超级计算广州中心/广州超级计算中心/应用部
* 广州市番禺区大学城外环东路132号






 

 
 
 
------------------ Original ------------------

**Comment by milanlanlan** [comment]
这样，那应该不是上传而是编码的问题，里面的内容是我之后测试覆盖掉了，现在我试一下重新跑

**Comment by milanlanlan** [comment]
好像可以了！虽然同样的代码我也不知道为什么，可能哪里改错了…… 谢谢，麻烦了！

**Comment by lijiang2014** [comment]
@milanlanlan  杜老师说你们那边测试有些问题，不知道是以前的还是新的？ 如果有发现新的问题请及时联系我。
另，对之前的一些问题进行了修复，目前main.py 里的所有测试可以通过。 
另对测试工具进行了一些改进：

`
[sysu_dwu_1@cn16356 pytest]$ python main.py help
Usage: python main.py [all/<test name >]
('<test name > could be : ', ['job', 'file', 'auth'])
`
使用 python main.py all 会进行所有的测试 
而 使用 python main.py job 只会测试 job 模块的API , 同理还有 file模块 和 auth 模块。
另外 ：

可以使用 python main.py job 0  只对 Job 模块中的第一个测试进行测试 。

再另外 ：

可以使用 python main.py run  cmd   可以测试运行一个命令 。
如 ：

`
[sysu_dwu_1@cn16356 pytest]$ python main.py run "which mpicc"
 run cmd :  which mpicc
jump to async
{u'status': u'OK', u'output': {u'output': u'/usr/local/mpi3-dynamic/bin/mpicc\n', u'retcode': 0, u'error': u''}, u'status_code': 200, u'error': u''}
/usr/local/mpi3-dynamic/bin/mpicc

`
目前，修改了 post /api/command 的接口，应该能直接正确解析大部分的SHELL 命令。

`
[sysu_dwu_1@cn16356 pytest]$ python main.py run "pwd;cd ~/coreos;mpicc main.cpp -o b.out; ./b.out"
 run cmd :  pwd;cd ~/coreos;mpicc main.cpp -o b.out; ./b.out
jump to async
{u'status': u'OK', u'output': {u'output': u'/HOME/sysu_dwu_1\n32767\n', u'retcode': 0, u'error': u''}, u'status_code': 200, u'error': u''}
/HOME/sysu_dwu_1
32767

`

**Comment by milanlanlan** [comment]
我没有跟杜老师联系过，也许是以前的？我们这边的话我已经pr了，但没有merged，不知道集成到网页中是否出问题，我去了解一下。
感谢你的测试文件，对我的帮助很大，我会继续完善这边的系统！

**Comment by milanlanlan** [comment]
您好，今天我们上线测试的时候发现 上传文件(upload_file)部分返回了` PermissionError at /api/file/ln3/HOME/sysu_dwu_1/main.cpp `这个错误，代码的主体部分基本没有改动，不知道是你们那边的权限改了，还是我们的问题呢？周末打扰，不好意思

**Comment by JiangLiNSCC** [comment]
/api/file/ln3/HOME/sysu_dwu_1/main.cpp 按说应该是有权限的，不知道系统哪里出的故障，我周一看看怎么回事，现在不方便操作。你暂时先试下其他路径能上传吗？ 
也有可能是 /HOME/sysu_dwu_1/main.cpp 这个文件已经存在了，所以出错?






------------------


------------------------------
* 典型性问题欢迎到下面的网址进行提问和搜索 ！
* https://github.com/JiangLiNSCC/TH2-demos/issues （推荐）
* Links : docs 搜索已有问题  提新问题
* 办公时间可联系： 020-37106035 （不推荐）
* 李江  国家超级计算广州中心/广州超级计算中心/应用部
* 广州市番禺区大学城外环东路132号






 

 
 
 
------------------ Original ------------------

**Comment by milanlanlan** [comment]
我也尝试过`/api/file/ln3/HOME/sysu_dwu_1/coreos/main.cpp `和 `/api/file/ln3/HOME/sysu_dwu_1/coreos/main_1.cpp` ，同样不行，很奇怪，之前同样的代码是可以的。
我打印出login的信息，auth也是true，应该没有问题。

**Comment by lijiang2014** [comment]
@milanlanlan  现在再试试还有没有问题 ? . 应该是之前服务没有以root起，产生的临时文件权限不够用。

**Comment by milanlanlan** [comment]
可以了，麻烦您了！

**Comment by milanlanlan** [comment]
你好，目前上线的版本测试下用g++好像已经可以通过了，根据老师的意思希望可以进一步测试并行程序，不知道现在可以使用了吗？例如mpicc。
打扰了

**Comment by JiangLiNSCC** [comment]
可以用，目前已经是在天河生产环境下跑了






------------------


------------------------------
* 典型性问题欢迎到下面的网址进行提问和搜索 ！
* https://github.com/JiangLiNSCC/TH2-demos/issues （推荐）
* Links : docs 搜索已有问题  提新问题
* 办公时间可联系： 020-37106035 （不推荐）
* 李江  国家超级计算广州中心/广州超级计算中心/应用部
* 广州市番禺区大学城外环东路132号






 

 
 
 
------------------ Original ------------------

**Comment by milanlanlan** [comment]
好的，谢谢！我去试试

**Comment by milanlanlan** [comment]
您好，目前我在测试运行并行程序的命令，印象中并不能直接用./而必须使用yhrun/yhbatch命令的，但是我忘记了分区名(-p ,,)，然后发现无法调用yhi查看(command not found)，不知道现在我应该怎样查呢？
目前不是特别熟悉天河2号的操作，问的问题有些简单，不好意思

**Comment by lijiang2014** [comment]
yhi 其实是 alias ， 所以用不了 ， 应用 yhinfo .

其实你加上 -p free 即可。

**Comment by milanlanlan** [comment]
抱歉，之前有些事暂停了一下。

之前我测试已经可以跑简单的demo了，但是最近发现登录被拒绝(connection refused)，不知道是哪里出了问题呢？

此外，关于编译语言方面，我目前只加上了`mpicc`，不知道具体还需要哪几种呢？我看了一下手册，好像更改编译环境需要用module进行配置，那么不同用户使用不同语言编译的时候如何解决这种环境配置的冲突呢？

还有，关于运行参数方面，我目前加上了-N -n 和 -c ，不知道还需要其他什么参数呢？吴老师让我问问你们。

打扰了。

**Comment by JiangLiNSCC** [comment]
哦 ，抱歉， 昨天不小心把服务关了，如有需要我再拉起来。
关于编译的问题过会儿我再写资料给你。





------------------


------------------------------
* 典型性问题欢迎到下面的网址进行提问和搜索 ！
* https://github.com/JiangLiNSCC/TH2-demos/issues （推荐）
* Links : docs 搜索已有问题  提新问题
* 办公时间可联系： 020-37106035 （不推荐）
* 李江  国家超级计算广州中心/广州超级计算中心/应用部
* 广州市番禺区大学城外环东路132号






 

 
 
 
------------------ Original ------------------

**Comment by milanlanlan** [comment]
好的，麻烦再次开一下吧

**Comment by lijiang2014** [comment]
这个当时已经重开了，忘了给你说了 ... ... 你们关于后面的权限和组的管理有规划了吗？ @milanlanlan

**Comment by milanlanlan** [comment]
好的，不过我们这边云虚拟机好像出了问题，暂时没法测试。
权限和组的管理，具体是指什么的权限呢？如果只是并行编程的话，应该是都可以吧？如果是网站本身的话，我们这边本身是有学生、教师和管理员三种权限，不知道你具体是指哪一种呢？

**Comment by JiangLiNSCC** [comment]
调用API ， 不同的用户身法需要怎么样的权限控制 





------------------


------------------------------
* 典型性问题欢迎到下面的网址进行提问和搜索 ！
* https://github.com/JiangLiNSCC/TH2-demos/issues （推荐）
* Links : docs 搜索已有问题  提新问题
* 办公时间可联系： 020-37106035 （不推荐）
* 李江  国家超级计算广州中心/广州超级计算中心/应用部
* 广州市番禺区大学城外环东路132号






 

 
 
 
------------------ Original ------------------

**Comment by milanlanlan** [comment]
目前用户不可以接触api，api对其不可见，用户只能运行代码。
请问需要提供吗？

**Comment by JiangLiNSCC** [comment]
恩，那就不用吧




------------------


------------------------------
* 典型性问题欢迎到下面的网址进行提问和搜索 ！
* https://github.com/JiangLiNSCC/TH2-demos/issues （推荐）
* Links : docs 搜索已有问题  提新问题
* 办公时间可联系： 020-37106035 （不推荐）
* 李江  国家超级计算广州中心/广州超级计算中心/应用部
* 广州市番禺区大学城外环东路132号






 

 
 
 
------------------ Original ------------------

**Comment by milanlanlan** [comment]
您好，由于云虚拟机的问题我今天才能测试，不过在运行上传函数时发现返回的是`http error 500：internal server error`，请问是我这边的问题吗？

**Comment by JiangLiNSCC** [comment]
我先看看 





------------------


------------------------------
* 典型性问题欢迎到下面的网址进行提问和搜索 ！
* https://github.com/JiangLiNSCC/TH2-demos/issues （推荐）
* Links : docs 搜索已有问题  提新问题
* 办公时间可联系： 020-37106035 （不推荐）
* 李江  国家超级计算广州中心/广州超级计算中心/应用部
* 广州市番禺区大学城外环东路132号






 

 
 
 
------------------ Original ------------------

**Comment by lijiang2014** [comment]
明白为啥了 ： 
```
[nscc-gz_jiangli@ln2%tianhe2-C logs]$ ps aux | grep celery
1870     12249  0.0  0.0 103264   892 pts/6    S+   15:40   0:00 grep celery
root     61684  0.0  0.0 119072  1164 ?        Ss   Dec19   0:00 SCREEN -S celery_worker
root     64290  0.3  0.0 368764 50664 pts/0    S+   Dec19  11:09 /HOME/nscc-gz_jiangli/.virtualenvs/py34env-rh6.5/bin/python3.4 /HOME/nscc-gz_jiangli/.virtualenvs/py34env-rh6.5/bin/celery -A newt worker -Q ln3 -l info --autoscale=24,4
1870     64296  0.0  0.0 370768 46856 pts/0    S+   Dec19   0:00 /HOME/nscc-gz_jiangli/.virtualenvs/py34env-rh6.5/bin/python3.4 /HOME/nscc-gz_jiangli/.virtualenvs/py34env-rh6.5/bin/celery -A newt worker -Q ln3 -l info --autoscale=24,4
1870     64297  0.0  0.0 370768 46868 pts/0    S+   Dec19   0:00 /HOME/nscc-gz_jiangli/.virtualenvs/py34env-rh6.5/bin/python3.4 /HOME/nscc-gz_jiangli/.virtualenvs/py34env-rh6.5/bin/celery -A newt worker -Q ln3 -l info --autoscale=24,4
1870     64298  0.0  0.0 370768 46868 pts/0    S+   Dec19   0:00 /HOME/nscc-gz_jiangli/.virtualenvs/py34env-rh6.5/bin/python3.4 /HOME/nscc-gz_jiangli/.virtualenvs/py34env-rh6.5/bin/celery -A newt worker -Q ln3 -l info --autoscale=24,4
1870     64299  0.0  0.0 370768 46848 pts/0    S+   Dec19   0:00 /HOME/nscc-gz_jiangli/.virtualenvs/py34env-rh6.5/bin/python3.4 /HOME/nscc-gz_jiangli/.virtualenvs/py34env-rh6.5/bin/celery -A newt worker -Q ln3 -l info --autoscale=24,4
[nscc-gz_jiangli@ln2%tianhe2-C logs]$ 
```
 更新的配置环境用了  --autoscale=24,4 ， 派生进程方式与之前不同，导致派生的worker 竟然不是root 身份 ， 稍等.

**Comment by lijiang2014** [comment]
你现在再试一下 可以了吗 ？ @milanlanlan

**Comment by milanlanlan** [comment]
嗯,上传是没有问题了，不过mpicc还是返回command not found，之前测试好像可以通过

**Comment by JiangLiNSCC** [comment]
你 echo $PATH 看看 里面有没有 /usr/local/mpi3-dynamic/bin ， 可能你帐号的环境变量有些问题 





------------------


------------------------------
* 典型性问题欢迎到下面的网址进行提问和搜索 ！
* https://github.com/JiangLiNSCC/TH2-demos/issues （推荐）
* Links : docs 搜索已有问题  提新问题
* 办公时间可联系： 020-37106035 （不推荐）
* 李江  国家超级计算广州中心/广州超级计算中心/应用部
* 广州市番禺区大学城外环东路132号






 

 
 
 
------------------ Original ------------------

**Comment by milanlanlan** [comment]
好的，我先继续测试一下看是不是我程序的问题，好像有点bug

**Comment by milanlanlan** [comment]
你好，发现了一个很奇怪的现象：同样的代码，运行多次会出现不同的结果：
1.正常运行，但是运行结果和以前的运行结果不一样，有时候会返回mpicc command not found，有时候不会，PATH里有 /usr/local/mpi3-dynamic/bin；
2.假设返回结果赋给tmpdata，有时会提示tmpdata["output"]中string indices must be integers，但是有时也可以正常返回；
3.依旧是http 500，这个比较罕见，不过现在就是这种情况。

最奇怪的是同样的代码会出现以上三种情况。此外，可能是我的心理作用，去掉bash -c后正常运行的概率比较高...

**Comment by milanlanlan** [comment]
补充：有时也会出现正常并行编译的结果，此外，第2种情况是直接返回一个数字，出现过0、87等等..

**Comment by lijiang2014** [comment]
感激你的调用方法好像有问题，能看下你们是怎么调用的吗？

**Comment by lijiang2014** [comment]
刚跑了遍测试，发现有些过不去了。。。
改了下部署方式竟然影响还蛮大的 ...

**Comment by milanlanlan** [comment]
是，我的代码跟以前一样，有很多返回结果都不同了，我觉得主要问题是返回结果不稳定..

**Comment by lijiang2014** [comment]
@milanlanlan 能看到是哪些API 经常出错吗 ？

**Comment by milanlanlan** [comment]
因为我主要使用的是`post /api/command/<machine>`，（具体命令例如yhrun）所以这个出错的是最多的，例如http 500、task running.. 和 直接返回字符串(B2、0..)，此外上传文件有时候也会出错，不过频率不高，login倒是没出现过问题。

**Comment by JiangLiNSCC** [comment]
把你 post /api/command/<machine> 的调用发我看看吧。
 




------------------


------------------------------
* 典型性问题欢迎到下面的网址进行提问和搜索 ！
* https://github.com/JiangLiNSCC/TH2-demos/issues （推荐）
* Links : docs 搜索已有问题  提新问题
* 办公时间可联系： 020-37106035 （不推荐）
* 李江  国家超级计算广州中心/广州超级计算中心/应用部
* 广州市番禺区大学城外环东路132号






 

 
 
 
------------------ Original ------------------
From: "milanlanlan"; 
Date: 2016年12月22日(星期四) 下午2:15
To: "JiangLiNSCC/eHPC"; 
Cc: "李  江"; "Comment"; 
Subject: Re: [JiangLiNSCC/eHPC] Some problems. (#7)

 

因为我主要使用的是post /api/command/<machine>，（具体命令例如yhrun）所以这个出错的是最多的，例如http 500、task running.. 和 直接返回字符串(B2、0..)，此外上传文件有时候也会出错，不过频率不高，login倒是没出现过问题。

**Comment by milanlanlan** [comment]
```
def run_command(self, command):
		tmpdata = self.open("/command/" + machine_name, data = {"command" : command})
		#print tmpdata
		if self.ret200() and type(tmpdata) == type({}):
			return tmpdata["output"]["output"]
		elif type(tmpdata) == type({}):
			return tmpdata["output"]["error"]
		else :
			return None
```

```
def ehpc_run(self, output_filename, path, task_number, cpu_number_per_task, node_number, language, partition = "free"):
	
		run_command = {
			"c++" : "./%s" % (output_filename),
			"mpicc" : "yhrun -n %s -p %s %s" % (task_number, partition, output_filename)
		}
		#print run_command[language]
		commands = 'cd %s;%s' % (path, run_command[language])
		run_output = self.run_command(commands)
		run_out = run_output or "No output."

		if run_output is None:
			run_out = "Request error."

		return run_out
```

**Comment by lijiang2014** [comment]
@milanlanlan  可能需要看一下你拼接的具体的commands ， 即 self.run_command(commands) 中 commands 的具体内容来方便我测试，探查出错的具体原因。
刚刚修复了一些 API file 中可能存在的问题 #14。
接下来可能会调试下 API JOB 中的问题。

我在调试过程中会导致API 不可用。

**Comment by milanlanlan** [comment]
里面的参数是接收前端返回的结果，目前我测试是：
```
path = "/HOME/sysu_dwu_1/coreos"
n = "4"
partition = "free"
output_filename = "a.out"
language = "mpicc"
```
所以命令应该是：
`"cd /HOME/sysu_dwu_1/coreos;yhrun -n 4 -p free a.out"`
当然，之前还有编译部分我没有给出，不过如果是a.out的话我跑出过正确结果，所以应该可以直接运行测试。

**Comment by JiangLiNSCC** [comment]
这个问题已经解决，其实是CLient 端代码的问题。 
修改查看 test/main_test_sysu.py




------------------


------------------------------
* 典型性问题欢迎到下面的网址进行提问和搜索 ！
* https://github.com/JiangLiNSCC/TH2-demos/issues （推荐）
* Links : docs 搜索已有问题  提新问题
* 办公时间可联系： 020-37106035 （不推荐）
* 李江  国家超级计算广州中心/广州超级计算中心/应用部
* 广州市番禺区大学城外环东路132号






 

 
 
 
------------------ Original ------------------

**Comment by milanlanlan** [comment]
好的，我看看问题出在哪里

**Comment by lijiang2014** [comment]
@milanlanlan 更新了测试的代码，修复了Client 的一些错误， 见 main-test.py 。 目前全部API 可通过测试。你们这个周末有测试计划吗？

**Comment by milanlanlan** [comment]
不知道这次更新和昨天的区别大吗？昨天更新之后我修改了部分代码，运行结果应该没有什么问题，不过目前我还在完成相应的前端部分才能集成到服务器，大概在周末就会上线测试目前这个功能了，如果没有问题我再进一步讨论参数设置问题。

**Comment by JiangLiNSCC** [comment]
稍有区别，对下载文件的API 有所影响。






------------------


------------------------------
* 典型性问题欢迎到下面的网址进行提问和搜索 ！
* https://github.com/JiangLiNSCC/TH2-demos/issues （推荐）
* Links : docs 搜索已有问题  提新问题
* 办公时间可联系： 020-37106035 （不推荐）
* 李江  国家超级计算广州中心/广州超级计算中心/应用部
* 广州市番禺区大学城外环东路132号






 

 
 
 
------------------ Original ------------------

**Comment by milanlanlan** [comment]
你好！目前这边基本跑通，然后老师让我进一步来询问以下参数方面到底怎样设置比较好？
目前我设置了-n  -c 和 -N 三种参数，通过下拉选择框提供给用户选择，不知道数值具体取多少比较好呢？
此外，关于语言方面，我看手册好像是需要通过module配置，但是如果多用户同时请求时改变配置好像并不现实..?不知道你们有没有什么方法解决呢？

**Comment by JiangLiNSCC** [comment]
-N -n -c 需要根据应用的规模来选用。
对于单纯的OMP 程序 ：
-c 可选 1 ～ 24 ；-n -N 固定为 1 
对于 单纯的MPI 程序 ： 
-c 不设（即默认1） ； -N  推荐为 1  ， -n < 24 即可
对于计算量较大的MPI 程序 ， 可采用 -n > 24 的情况 。
---------------------------------------------------------------------------
另外 ， 每个用户设置自己的，调用 command 或 job API , 将 module 写在 command 命令 或 JOB 文件里即可 。  

 




------------------


------------------------------
* 典型性问题欢迎到下面的网址进行提问和搜索 ！
* https://github.com/JiangLiNSCC/TH2-demos/issues （推荐）
* Links : docs 搜索已有问题  提新问题
* 办公时间可联系： 020-37106035 （不推荐）
* 李江  国家超级计算广州中心/广州超级计算中心/应用部
* 广州市番禺区大学城外环东路132号






 

 
 
 
------------------ Original ------------------
From: "milanlanlan"; 
Date: 2016年12月30日(星期五) 下午4:58
To: "JiangLiNSCC/eHPC"; 
Cc: "李  江"; "Comment"; 
Subject: Re: [JiangLiNSCC/eHPC] Some problems. (#7)

 

你好！目前这边基本跑通，然后老师让我进一步来询问以下参数方面到底怎样设置比较好？
 目前我设置了-n  -c 和 -N 三种参数，通过下拉选择框提供给用户选择，不知道数值具体取多少比较好呢？
 此外，关于语言方面，我看手册好像是需要通过module配置，但是如果多用户同时请求时改变配置好像并不现实..?不知道你们有没有什么方法解决呢？

**Comment by milanlanlan** [comment]
你好，我们老师的意思是关于设置什么参数、参数值的范围应该由超算方面根据需求确定，我们这边来负责实现，而且希望可以多些参数值的选择，或许下次开会讨论一下？
另外，我记得关于这个在线系统的实现是前端所有用户对应一个天河帐号，可以在一个天河帐号内配置多个用户的module吗？
谢谢！
